# Generated by Django 5.2.5 on 2025-10-20 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="duration_seconds",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="passed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="total_points",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="QuizAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_answer", models.TextField(blank=True, null=True)),
                ("boolean_answer", models.BooleanField(blank=True, null=True)),
                ("points_earned", models.IntegerField(default=0)),
                ("is_correct", models.BooleanField(default=False)),
                ("feedback", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quiz.quizattempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quiz.question",
                    ),
                ),
                (
                    "selected_choices",
                    models.ManyToManyField(
                        blank=True, related_name="selected_in", to="quiz.choice"
                    ),
                ),
            ],
        ),
    ]
