# Generated by Django 5.2.5 on 2025-10-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_quizattempt_duration_seconds_quizattempt_passed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(
                blank=True,
                help_text="Correct answer for text or true/false questions",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="points",
            field=models.IntegerField(default=1),
        ),
    ]
