# Generated by Django 5.2.5 on 2025-10-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_question_correct_answer_question_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="allow_retake",
            field=models.BooleanField(
                default=False,
                help_text="Whether students can retake the quiz if they fail",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="passing_score",
            field=models.FloatField(
                default=50.0, help_text="Minimum percentage required to pass the quiz"
            ),
        ),
    ]
