# Generated by Django 5.2.5 on 2025-10-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_quiz_allow_retake_quiz_passing_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="last_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="marks_synced",
            field=models.BooleanField(default=False),
        ),
    ]
